vars:
  - params.yaml          # makes ${run_name}, ${base_model.repo}, ${family}, …

stages:
# ─────────────────────────────────────────────── merge
  merge:
    cmd: >
      python -m model_lab.merge_adapters
      --base     "${base_model.repo}"
      --adapter  models/hf/wip/${family}/${run_name}
      --out      models/hf/candidates/${family}/${run_name}_merged
    deps:
      - src/model_lab/merge_adapters.py
      - models/hf/wip/${family}/${run_name}
    outs:
      - models/hf/candidates/${family}/${run_name}_merged

# ─────────────────────────────────────────────── gguf
  gguf:
    cmd: >
      python -m model_lab.tools.convert_to_gguf models/hf/candidates/${family}/${run_name}_merged --out_file models/gguf/${family}/${run_name}_full.gguf
    deps:
      - src/model_lab/tools/convert_to_gguf.py
      - models/hf/candidates/${family}/${run_name}_merged
    outs:
      - models/gguf/${family}/${run_name}_full.gguf

# ─────────────────────────────────────────────── quant
  quant:
    cmd: >
      python -m model_lab.tools.quantize_gguf  models/gguf/${family}/${run_name}_full.gguf models/gguf/${family}/${run_name}_${ci.quant_mode}.gguf ${ci.quant_mode}
    deps:
      - src/model_lab/tools/quantize_gguf.py
      - models/gguf/${family}/${run_name}_full.gguf
    outs:
      - models/gguf/${family}/${run_name}_${ci.quant_mode}.gguf

  modelfile:
    cmd: >
       python -m model_lab.tools.generate_modelfile models/gguf/${family}/${run_name}_${ci.quant_mode}.gguf --template Modelfile.template --ctx_length ${modelfile.ctx_length} --system_prompt "${modelfile.system_prompt}" --out models/modelfiles/${family}/${run_name}_${ci.quant_mode}.Modelfile
    deps:
      - src/model_lab/tools/generate_modelfile.py
      - Modelfile.template
      - models/gguf/${family}/${run_name}_${ci.quant_mode}.gguf
    outs:
      - models/modelfiles/${family}/${run_name}_${ci.quant_mode}.Modelfile

  # ─────────────────────────────────────────────── eval
  eval_ci:
    cmd: >
      python -m model_lab.eval
      --model   models/hf/candidates/${family}/${run_name}_merged
      --dataset ${eval.path}
      --batch   ${eval.batch_size}
      --max-len ${eval.max_length}
      --offload
    deps:
      - src/model_lab/eval.py
      - models/hf/candidates/${family}/${run_name}_merged
    metrics:
      - metrics/${family}/${run_name}.json:
          cache: false
    outs:
    - metrics/${family}/archive 

  # ─────────────────────────────────────────────── docker
  docker:
    cmd: powershell -ExecutionPolicy Bypass -NoProfile -File .\Scripts\build_image_ci.ps1 qwen run-000 q4_k_m
    deps:
      - Scripts/build_image_ci.ps1
      - Dockerfile.serve
      # CORRECTED DEPENDENCY: Now correctly points to the Modelfile with the quant_mode suffix.
      - models/modelfiles/${family}/${run_name}_${ci.quant_mode}.Modelfile
      - models/gguf/${family}/${run_name}_full.gguf
      - models/gguf/${family}/${run_name}_${ci.quant_mode}.gguf
    outs:
      - .ci/image_${family}_${run_name}.txt